language: node_js
cache:
  directories:
    - node_modules
script:
  - npm run build:breakpoints && node --harmony ./node_modules/preston-core/bin/preston-sprite --dir=icons/ --configDir=_config/ && node --harmony ./node_modules/preston-core/bin/preston-build --outputDir=_dist/ --configDir=_config/
  - npm run test
deploy:
  provider: npm
  email: hamant.brahmbhatt@gmail.com
  skip_cleanup: true
  api_key:
    secure: l9fBaZDItcNKy6xSzzv5dCPKsSxsf38bhHscK2mptaybvJQZ4YTUex7O2oZ0pqT7WWTEF8vmF/ZrUxV9Hch7rO4puGSjJA2ROXg4JpNkAXY/EQXeX1ZxuPbTCc+ZxT0xKFGH9WGgHfAZxCFWm7dUddOFQErOVvTUiOyfY/xwRgNaFnV3Me0hmQFShE3eZazdTev2/JgVwxRDV+ABkDNWTNHKGwWbXAuN5ImDY8cBu8DfyJHid0KRPlvhKmBLdYZvtO9VKzS3HxbLHxeJxaSzKaVNjm9l3Jix2h/ygRsvhoW+O91BhwExyDVz4Zh6j6w/HiXqhQEdDHbgpw/E8HoiGgqmktasH2Qi4Ftm+yR/xOS98td+DdHPJHLnIlhsK/fXEGumog6EiCkNKlXt5C2o6ZEyhIA6XvPkzBwSIlwjqVMH+Cb13ppCS2j+mpOdnUOpLYqOWM7I3sQFa4ltPk6fYiG2WsnQhrQnqklSPd2e6SZg2d1xp+6QyF6U4C/x803HdaARkuLqr1DJD4DBulR4sy4QWbdDyBQ/21gdZKAfoqQMyR7S/Uzd4vGqHUpSBLVQzOps+bzcsN760uCggsaLqP1kctxzo3yMFOWwz+ZqYxb7/DUzCCN7ibMFSrzbRePmippkUTCpa77fVRMeP6PxB3B17mqfLXauBtjs2hg2pE0=
  on:
    tags: true
    repo: NET-A-PORTER/outnet-2015
after_deploy:
  - node --harmony ./node_modules/preston-core/bin/preston-publish --dir=_dist/ --configDir=_config/
# notifications:
#   webhooks:
#     urls:
#       - https://preston-nap-pr-generator.herokuapp.com/webhook
#     on_success: always
#     on_failure: never
